source:      .
destination: ./_site
layouts:     ./_layouts

#Config
exclude:      ["manifest.json"]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"

# Server
host:             0.0.0.0
port:             8000
baseurl:          /
encoding:         UTF-8

